# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-30 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coffee',
            fields=[
                ('coffee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('coffee_en_name', models.CharField(max_length=255, unique=True)),
                ('coffee_name', models.CharField(max_length=255, unique=True)),
                ('coffee_price', models.CharField(max_length=255)),
                ('coffee_image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='coffee_coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(default=None, max_length=40)),
                ('user_coupon_number', models.CharField(default=None, max_length=1024)),
                ('coffee_coupon_number', models.CharField(default=None, max_length=1024)),
                ('user_coupon_validity_date', models.CharField(default=None, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='coffee_order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('coffee_en_name', models.CharField(max_length=255)),
                ('coffee_name', models.CharField(max_length=255)),
                ('coffee_count', models.IntegerField()),
                ('openid', models.CharField(default=None, max_length=40)),
                ('trade_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='coffee_trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_en_name', models.CharField(max_length=255)),
                ('coffee_name', models.CharField(max_length=255)),
                ('openid', models.CharField(default=None, max_length=40)),
                ('valid', models.CharField(default=0, max_length=30)),
                ('trade_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
